const CONFIG = {
  github: {
    username: 'shahpratham00-collab',
  },
  base: '/',
  projects: {
    github: {
      display: true,
      header: 'Projects',
      mode: 'automatic',
      automatic: {
        sortBy: 'updated',
        limit: 8,
        exclude: {
          forks: false,
          projects: [],
        },
      },
    },
    external: {
      header: 'Live Deployments',
      projects: [
        {
          title: 'RAG Job Application Assistant',
          description:
            'Production RAG system using LangChain, Llama3, FAISS and Streamlit. Deployed live on Streamlit Cloud.',
          imageUrl: '',
          link: 'https://rag-job-application-assistant-snwzr5zwdf8throdarxizd.streamlit.app/',
        },
        {
          title: 'NLP Sentiment Analyser — DistilBERT',
          description:
            'DistilBERT fine-tuned on SST-2, benchmarked against LR and SVM baselines. Live on Streamlit Cloud.',
          imageUrl: '',
          link: 'https://sentiment-analyser-nlp-m5wbhmnnfoijsvapc24zft.streamlit.app/',
        },
        {
          title: 'Industrial Defect Detection CNN',
          description:
            'Deep CNN achieving 95.28% accuracy on steel surface defect classification. ONNX deployed.',
          imageUrl: '',
          link: 'https://defect-detection-cnn-cykjxqqen4gqptgmeequad.streamlit.app/',
        },
      ],
    },
  },
  seo: {
    title: 'Pratham Shah — ML Engineer Portfolio',
    description:
      'MSc AI & Data Science student at NTU. 7 AI/ML projects built and deployed. Seeking ML Engineer roles in the UK.',
    imageURL: '',
  },
  social: {
    linkedin: 'prathamshah16',
    twitter: '',
    mastodon: '',
    researchGate: '',
    facebook: '',
    instagram: '',
    reddit: '',
    threads: '',
    youtube: '',
    udemy: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    skype: '',
    telegram: '',
    website: '',
    phone: '',
    email: 'prathamshah1516@gmail.com',
  },
  resume: {
    fileUrl: '',
  },
  skills: [
    'Python',
    'Machine Learning',
    'Deep Learning',
    'NLP',
    'LangChain',
    'RAG',
    'TensorFlow',
    'PyTorch',
    'HuggingFace',
    'Scikit-learn',
    'XGBoost',
    'FAISS',
    'Apache Kafka',
    'Apache Spark',
    'AWS',
    'Docker',
    'SQL',
    'Streamlit',
    'Gradio',
  ],
  experiences: [
    {
      company: 'Viacom18 Media Private Limited',
      position: 'Data & Systems Analyst Intern',
      from: 'December 2022',
      to: 'June 2024',
      companyLink: '',
    },
    {
      company: 'Pantech Solutions',
      position: 'Data & IoT Analyst Intern',
      from: 'January 2022',
      to: 'June 2022',
      companyLink: '',
    },
    {
      company: 'E-Yantra Lab — IIT Bombay',
      position: 'Research & Embedded Systems Intern',
      from: 'August 2021',
      to: 'September 2021',
      companyLink: '',
    },
  ],
  certifications: [
    {
      name: 'Google Cloud Professional Developer',
      body: 'Google',
      year: '2022',
      link: '',
    },
    {
      name: 'SQL Bootcamp with MySQL, PHP & Python',
      body: 'Udemy',
      year: '2021',
      link: '',
    },
    {
      name: 'Google Data Studio / Looker Studio A-Z',
      body: 'Google',
      year: '2022',
      link: '',
    },
    {
      name: 'The Data Science Course',
      body: 'Udemy',
      year: '2020',
      link: '',
    },
  ],
  educations: [
    {
      institution: 'Nottingham Trent University',
      degree: 'MSc Artificial Intelligence & Data Science',
      from: '2025',
      to: 'Present',
    },
    {
      institution: 'University of Mumbai',
      degree: 'B.E. Electronics & Telecommunication Engineering',
      from: '2021',
      to: '2024',
    },
  ],
  publications: [],
  blog: {
    display: false,
  },
  googleAnalytics: {
    id: '',
  },
  hotjar: {
    id: '',
    snippetVersion: 6,
  },
  themeConfig: {
    defaultTheme: 'dark',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
    ],
    customTheme: {
      primary: '#1d9e75',
      secondary: '#378add',
      accent: '#37cdbe',
      neutral: '#0a0f1e',
      'base-100': '#0a0f1e',
      '--rounded-box': '3px',
      '--rounded-btn': '3px',
    },
  },
  footer: 'Made with GitProfile — Pratham   Shah 2026',
  enablePWA: true,
};

export default CONFIG;
